# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            script:
              - IMAGE_NAME=$BITBUCKET_REPO_SLUG
              - cd bnitdoc-builder
              - docker build . --file Dockerfile --tag ${IMAGE_NAME_BUILDER}
              - docker build . --file DockerfileDev --tag ${IMAGE_NAME_DEV}
              - cd ../bnitdoc-collector
              - docker build . --file Dockerfile --tag ${IMAGE_NAME_COLLECTOR}
            services:
              - docker
            caches:
              - docker
        - step:
            name: Lint the Dockerfile
            image: hadolint/hadolint:latest-debian
            script:
              - hadolint Dockerfile
  branches:
    master:
      - step:
          name: Build and Test
          script:
            - IMAGE_NAME_DEV=${BITBUCKET_REPO_SLUG}
            - IMAGE_NAME_BUILDER=${BITBUCKET_REPO_SLUG}-builder
            - IMAGE_NAME_COLLECTOR=${BITBUCKET_REPO_SLUG}-collector
            - cd bnitdoc-builder
            - docker build . --file Dockerfile --tag ${IMAGE_NAME_BUILDER}
            - docker save ${IMAGE_NAME_BUILDER} --output "../${IMAGE_NAME_BUILDER}.tar"
            - docker build . --file DockerfileDev --tag ${IMAGE_NAME_DEV}
            - docker save ${IMAGE_NAME_DEV} --output "../${IMAGE_NAME_DEV}.tar"
            - cd ../bnitdoc-collector
            - docker build . --file Dockerfile --tag ${IMAGE_NAME_COLLECTOR}
            - docker save ${IMAGE_NAME_COLLECTOR} --output "../${IMAGE_NAME_COLLECTOR}.tar"
          services:
            - docker
          caches:
            - docker
          artifacts:
            - "*.tar"
      - step:
          name: Deploy to Production
          deployment: Production
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - VERSION="prod-0.1.${BITBUCKET_BUILD_NUMBER}"
            - IMAGE_NAME=${BITBUCKET_REPO_SLUG}
            - docker load --input "${IMAGE_NAME}.tar"
            - IMAGE=${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
            - docker push "${IMAGE}:${VERSION}"
            - IMAGE_NAME=${BITBUCKET_REPO_SLUG}-builder
            - docker load --input "${IMAGE_NAME}.tar"
            - IMAGE=${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
            - docker push "${IMAGE}:${VERSION}"
            - IMAGE_NAME=${BITBUCKET_REPO_SLUG}-collector
            - docker load --input "${IMAGE_NAME}.tar"
            - IMAGE=${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
            - docker push "${IMAGE}:${VERSION}"
          services:
            - docker
